services:
  postgres:
    container_name: py-postgres
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=speedrun
    ports:
      - "5432:5432"
    restart: always